# Generated by Django 3.2.5 on 2021-08-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
